# Generated by Django 4.2.24 on 2025-09-13 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="username"
                    ),
                ),
                ("is_company", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "salary_range",
                    models.CharField(
                        choices=[
                            ("upto_1000", "Até 1.000"),
                            ("1000_2000", "De 1.000 a 2.000"),
                            ("2000_3000", "De 2.000 a 3.000"),
                            ("above_3000", "Acima de 3.000"),
                        ],
                        max_length=30,
                    ),
                ),
                ("requirements", models.TextField(blank=True)),
                (
                    "min_education",
                    models.CharField(
                        choices=[
                            ("fundamental", "Ensino fundamental"),
                            ("medio", "Ensino médio"),
                            ("tecnologo", "Tecnólogo"),
                            ("superior", "Ensino Superior"),
                            ("pos", "Pós / MBA / Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_expectation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("experience", models.TextField(blank=True)),
                (
                    "last_education",
                    models.CharField(
                        choices=[
                            ("fundamental", "Ensino fundamental"),
                            ("medio", "Ensino médio"),
                            ("tecnologo", "Tecnólogo"),
                            ("superior", "Ensino Superior"),
                            ("pos", "Pós / MBA / Mestrado"),
                            ("doutorado", "Doutorado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("score", models.IntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.job",
                    ),
                ),
            ],
        ),
    ]
